name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots.
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Development (local)
        - Preview deployment
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 120, Safari 17
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g. 18.17.0
